### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xyumt** [xiaowine/miui.statusbar.lyric#13]
手机重启之后模块失效，需要重启系统界面才能生效，望解决，本人很喜欢这个模块

**Comment by xiaowine** [comment]
> 手机重启之后模块失效，需要重启系统界面才能生效，望解决，本人很喜欢这个模块

找不到问题所在

**Comment by SpeedPartner** [comment]
一样问题...

**Comment by SpeedPartner** [comment]
> > 手机重启之后模块失效，需要重启系统界面才能生效，望解决，本人很喜欢这个模块
> 
> 找不到问题所在

2.21.37正常,之后版本重启设备就不行了,需要手动重启系统界面
