### ISSUE TITLE
点开其他app卡顿

### ISSUE THREAD

**Issue by cris0828** [xiaowine/miui.statusbar.lyric#14]
目前在网易云音乐和椒盐音乐都遇到过，在桌面点开其他app，会卡顿，100%复现，但是在后台卡片切换就不会

**Comment by xiaowine** [comment]
> 目前在网易云音乐和椒盐音乐都遇到过，在桌面点开其他app，会卡顿，100%复现，但是在后台卡片切换就不会

k20一切正常，请检查其它软件
