### ISSUE TITLE
锁屏歌词

### ISSUE THREAD

**Issue by Zruiry** [xiaowine/miui.statusbar.lyric#16]
**环境信息**

模块版本: 3.22.45
MIUI版本: 12.5.13
Android版本: 11
屏幕类型: 四曲面AMOLED柔性屏

**在最新的release版本中能否复现**
是
**bug内容**

解锁状态歌词正常显示，歌词长的时候可以覆盖右边图标，锁屏状态歌词长的话无法覆盖右边图标，导致歌词与图标同时显示造成重合
**复现方法**

找一个歌词长的歌曲播放然后锁屏

**Comment by xiaowine** [comment]
> **环境信息**
> 
> 模块版本: 3.22.45 MIUI版本: 12.5.13 Android版本: 11 屏幕类型: 四曲面AMOLED柔性屏
> 
> **在最新的release版本中能否复现** 是 **bug内容**
> 
> 解锁状态歌词正常显示，歌词长的时候可以覆盖右边图标，锁屏状态歌词长的话无法覆盖右边图标，导致歌词与图标同时显示造成重合 **复现方法**
> 
> 找一个歌词长的歌曲播放然后锁屏

是否覆盖右边图标，是系统自己决定，模块没有改变。所以是系统bug
