### ISSUE TITLE
K40安卓12不能用

### ISSUE THREAD

**Issue by chengjin12138** [xiaowine/miui.statusbar.lyric#4]
K40安卓12不能用

**Comment by 577fkj** [comment]
android 12最新版已支持

**Comment by chengjin12138** [comment]
那我真是太惨了


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月5日(周五) 晚上10:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaowine/miui.statusbar.lyric] K40安卓12不能用 (Issue #4)




 
android 12最新版已支持
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
