### ISSUE TITLE
systemui重载

### ISSUE THREAD

**Issue by Eiyuuzaki** [xiaowine/miui.statusbar.lyric#5]
系统 MIUI12.5 | 21.8.31 (开发版)
具体情况表现为正常使用手机且播放歌曲(状态栏歌词正常)的情况下黑屏，systemui重载后进入锁屏界面。
Log在这里:https://wwr.lanzoui.com/b02ohfedg
密码:2aav

**Comment by xiaowine** [comment]
> 系统 MIUI12.5 | 21.8.31 (开发版) 具体情况表现为正常使用手机且播放歌曲(状态栏歌词正常)的情况下黑屏，systemui重载后进入锁屏界面。 Log在这里:https://wwr.lanzoui.com/b02ohfedg 密码:2aav

使用模块能的 重置模块 再试试

**Comment by Eiyuuzaki** [comment]
按照你说的重置模块 但这个问题还是可以复现(一直是没法主动复现而是被动复现)

**Comment by xiaowine** [comment]
> 按照你说的重置模块 但这个问题还是可以复现(一直是没法主动复现而是被动复现)

把使用统计关了试试，报错与配置文件有关

**Comment by Eiyuuzaki** [comment]
已经关了 如果还有bug我会带上log来反馈的

**Comment by xiaowine** [comment]
> 已经关了 如果还有bug我会带上log来反馈的

感谢

**Comment by 577fkj** [comment]
更新到最新版 如果还有出现请附上log
