### ISSUE TITLE
网易云8.6.02

### ISSUE THREAD

**Issue by Y-NanLi** [xiaowine/miui.statusbar.lyric#8]
网易云8.6.02听歌状态栏不显示歌词 需要重启系统UI才显示
网易云8.6.02听歌状态栏不显示歌词 需要重启系统UI才显示

**Comment by xiaowine** [comment]
> 网易云8.6.02听歌状态栏不显示歌词 需要重启系统UI才显示 网易云8.6.02听歌状态栏不显示歌词 需要重启系统UI才显示

每次都是？

**Comment by xiaowine** [comment]
> 网易云8.6.02听歌状态栏不显示歌词 需要重启系统UI才显示 网易云8.6.02听歌状态栏不显示歌词 需要重启系统UI才显示

每次都是？

**Comment by Y-NanLi** [comment]
重启手机后每次都要打开模块重启系统UI，不听歌一段时间后，再想听歌还要重启系统UI

**Comment by 577fkj** [comment]
> 重启手机后每次都要打开模块重启系统UI，不听歌一段时间后，再想听歌还要重启系统UI

最新版我测试已经没有此问题

**Comment by Y-NanLi** [comment]
可能是我的手机问题吧😂 我的是k20pro

**Comment by zhangsiyu0** [comment]
遇到同样的问题，开机重启后状态栏不显示歌词，需要手动重启系统ui才可以使用。

**Comment by xiaowine** [comment]
> 遇到同样的问题，开机重启后状态栏不显示歌词，需要手动重启系统ui才可以使用。

重新优化系统界面

**Comment by xiaowine** [comment]
> 可能是我的手机问题吧😂 我的是k20pro

重新优化系统界面

**Comment by zhangsiyu0** [comment]
> > 遇到同样的问题，开机重启后状态栏不显示歌词，需要手动重启系统ui才可以使用。
> 
> 重新优化系统界面

还是不行，看了下日志是重启后未hook系统界面，手动重启系统界面后才hook成功。

**Comment by xiaowine** [comment]
> > > 遇到同样的问题，开机重启后状态栏不显示歌词，需要手动重启系统ui才可以使用。
> > 
> > 
> > 重新优化系统界面
> 
> 还是不行，看了下日志是重启后未hook系统界面，手动重启系统界面后才hook成功。

这个其实不属于我们的范围,是xp的问题
