### ISSUE TITLE
切换歌词动效导致的系统UI重启

### ISSUE THREAD

**Issue by ShanshanHY** [xiaowine/miui.statusbar.lyric#9]
> 机型: 
k30pro

> 系统版本: 
21.11.3

> 问题详情: 
切换歌词动效为[下滑]后必定导致系统ui重启，被动重启后模块失效  在此之后主动重启系统ui，小概率切换成功，大概率模块失效  
另: 切换为[右滑]/[左滑]也均有此现象发生(之前只有右滑有问题，清除全部数据后左滑也有问题)

> 错误日志: 
[点击下载](https://www.lanzouw.com/iBFA9w79m5a)

**Comment by xiaowine** [comment]
> > 机型:
> > k30pro
> 
> > 系统版本:
> > 21.11.3
> 
> > 问题详情:
> > 切换歌词动效为[下滑]后必定导致系统ui重启，被动重启后模块失效  在此之后主动重启系统ui，小概率切换成功，大概率模块失效
> > 另: 切换为[右滑]/[左滑]也均有此现象发生(之前只有右滑有问题，清除全部数据后左滑也有问题)
> 
> > 错误日志:
> > [点击下载](https://www.lanzouw.com/iBFA9w79m5a)

K20测试没任何问题

**Comment by ShanshanHY** [comment]
经过本人日志排查，发现这个问题是由于对模块开启了 [存储空间隔离] 导致其在对配置文件/sdcard/Android/media/miui.statusbar.lyric/Config.json修改时发生错误，关掉即可正常

更具体的内部原因暂时不清楚，但希望作者可以在模块处增加提醒，或尝试去解决(例如更换配置文件所在目录)
